### ISSUE TITLE
Do you have an example how to use Get-CMMachineVariable ?

### ISSUE THREAD

**Issue by KurtDeGreeff** [jpscripter/CMManagement#1]
How can I set a secret in a script/CI/package and how to retrieve it later?
Thanks

**Comment by jpscripter** [comment]
It depends on your risk tolerance. CM encrypts variables in transit natively and that is what Get-CMMachineVariable uses. You would select the machine in the cm console, add a variable, that variable can be masked in the console or not but is encrypted by the provider in the database, then added to policy and sent to the client for decryption and storying using the DPAPI for local storage. This reverses that DPAPI encryption and retrieves the variable locally. Microsoft uses a process similar to this for the network service account and other secrets, but if this isn't secure enough, you would want to use your own symmetric encryption on top of this. Something like:

Encoding:
$Userinput = 'someParam2Secure'
$keybytes = [System.Text.Encoding]::UTF8.GetBytes($Userinput)
[Byte[]] $Key = [System.Security.Cryptography.HashAlgorithm]::Create('SHA256').ComputeHash($keybytes)
$secure = ConvertTo-SecureString -String ‘Password123' -AsPlainText -Force 
ConvertFrom-SecureString -SecureString $secure -Key $key

Decoding:
$securestring2 = ConvertTo-SecureString -Key $key -String 
'76492d1116743f0423413b16050a5345MgB8AGMASwBCAE0ASABWAEEASABCAGkAZgBLAGgAUABrAFcA
MwBGAEEAcgB5AEEAPQA9AHwAMAAwADcAMQBlADkAMwBhAGUAZABlAGEAMgBjADAANwBiADkAYQA
zADkANQBkADIANgBiADIANgAzAGQAZgBlAA=='
[System.Runtime.InteropServices.marshal]::PtrToStringAuto([System.Runtime.InteropServices.marshal]::Secu
reStringToBSTR($securestring))

**Comment by jpscripter** [comment]
But to answer your question, there isn't a great way to do this natively (in my opinion). Using the cm machine variables is a way but adding the variable to the machines\collection can be annoying. For packages and task sequences, you could just add the symmetric decryption code to your script and use a parameter to pass in the key, but this doesn't really work for scripts or CIs. The main key here is that you want to keep the key and the encrypted secret in separate locations to make it more difficult to combine and decrypt. Does that help?

**Comment by jpscripter** [comment]
Closing the issue for how. let me know if you have more questions.
